# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_img', models.CharField(max_length=200)),
                ('p_description', models.CharField(max_length=1000)),
                ('p_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=250)),
                ('t_img', models.CharField(max_length=1000)),
                ('t_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Type'),
        ),
    ]
