# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20170522_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='p_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
